blank_issues_enabled: false
contact_links:
  - name: Have a question or feature request?
    about: "Start discussion, ask a question or request a new feature"
    url: https://github.com/GameBridgeAI/ts_serialize/discussions/new
  - name: Getting started developing ts_serialize
    about: "Our steps to help set up a local version of the project"
    url: https://github.com/GameBridgeAI/ts_serialize/blob/develop/.github/DEVELOPMENT.md
  - name: How to contribute
    about: "The steps for submitting to ts_serialize"
    url: https://github.com/GameBridgeAI/ts_serialize/blob/develop/.github/CONTRIBUTING.md
  - name: Code of conduct
    about: "Please make sure to adhere to our code of conduct"
    url: https://github.com/GameBridgeAI/ts_serialize/blob/develop/.github/CODE_OF_CONDUCT.md